### ISSUE TITLE
FS API breakage 2 years ok causes kitchensink to not compile

### ISSUE THREAD

**Issue by Guthur** [puppetlabs/clj-kitchensink#60]
raynes/fs broke their API here https://github.com/Raynes/fs/commit/8fadbde3461ad1870468a0ee0991662d55f5f640

Which causes puppetlabs/kitchensink to fail due to it's use of fs/absolute-path.

Is this known? and is there some workaround I am missing?

Cheers,

**Comment by tdavis** [comment]
I've finally been arsed to file this on their [bug tracker](https://tickets.puppetlabs.com/browse/TK-315) but in the meantime feel free to just use my [fork](https://clojars.org/org.clojars.tdavis/kitchensink)

**Comment by cprice404** [comment]
This is fixed in the latest releases.
